# site name
siteName: さくら荘その
shortName: hojun
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://sakura.hojun.cn
description: 好少年光芒万丈
cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.5

notice: hexo-Sakura主题已经开源，目前正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.5/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /video, fa: fa-film faa-vertical }, 
    歌单: {path: /music, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links, fa: fa-link faa-shake }
  赞赏: { path: /donate, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about, fa: fa-meetup}, 
    主题: {path: /theme-sakura, fa: iconfont icon-sakura },
    Lab: {path: /lab, fa: fa-cogs },
  } }
  客户端: { path: /client, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false



# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片
bgn: 8

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018


# cover info config
coverTitle: 
coverDescription: XXX的博客

#social  url, img PC端配置
social:
  github: {url: http://github.com/honjun, img: /img/social/github.png}
  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  alipay: /img/custom/donate/AliPayQR.png
  wechat: /img/custom/donate/WeChanQR.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4



# Git-pages server info
gitPageServerName: Github Pages
gitPageServerUrl: https://github.com/
codingPageServerName: Coding Pages
codingPageServerUrl: https://pages.coding.me